name: ggtdd_app
description: A new Flutter project.

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/Ellipse_43.png
    - assets/images/Ellipse_45.png
    - assets/images/Ellipse_44.png
    - assets/images/to-do-list.png
    - assets/images/man.png
    - assets/images/details_1.png
    - assets/images/critical-thinking_1.png
    - assets/images/inbox_1.png
    - assets/images/communication-skills_1.png
    - assets/images/loop_1.png
    - assets/images/improve_1.png
